POST  http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "dangtuthieu",
    "password": "123456",
    "email": "dangtuthieu@gmail.com"
}


###
GET http://localhost:5000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY0OTc1MjUwNSwiZXhwIjoxNjUwMDExNzA1fQ.N9SSL3dNSKYg-irhVGg8XcfNhbFM6O8I9FX4TAus0-8


###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"ntneik15@gmail.com",
    "password":"123456"
}

###
POST  http://localhost:5000/api/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MDExNjkzNiwiZXhwIjoxNjUwMzc2MTM2fQ.KDdtRBtFRck2oSctzWkqd6kraZT3lz1V6Q8tkDpX3ts

{
    "name": "Phòng 112",
    "roomtype": "625192936804590ec7d86661",
    "charge": "625191366804590ec7d86660",
    "description": "create",
    "status":"Waiting"
}

###
GET http://localhost:5000/api/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTU2OWJiOWIxZTQxNjhhZmNhNzc3NSIsImlhdCI6MTY0OTg0OTA3OCwiZXhwIjoxNjUwMTA4Mjc4fQ.6AVZLNBHbz8fuqvX5eCfrKDPh_tAcD9_6woVqFQJreY

###
PUT  http://localhost:5000/api/room/625c753e9069c3c7962d0a35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MDExNjkzNiwiZXhwIjoxNjUwMzc2MTM2fQ.KDdtRBtFRck2oSctzWkqd6kraZT3lz1V6Q8tkDpX3ts

{
    "_id": "625c753e9069c3c7962d0a35",
    "name": "Phòng 1.1",
    "roomtype": "625192936804590ec7d86661",
    "charge":"625191366804590ec7d86660",
    "description": "create",
    "status": "Booked",
    "__v": 1
}

###
DELETE http://localhost:5000/api/room/625c80cb531bb42720ee81e1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MDExNjkzNiwiZXhwIjoxNjUwMzc2MTM2fQ.KDdtRBtFRck2oSctzWkqd6kraZT3lz1V6Q8tkDpX3ts

###
GET http://localhost:5000/api/invoice
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY0OTQ5NDg3MiwiZXhwIjoxNjQ5NzU0MDcyfQ.8orKhuSHV3XH6gUD_BkQN60ekApHoFy1k53gme90MSg

###
POST  http://localhost:5000/api/invoice
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY0OTc1MjUwNSwiZXhwIjoxNjUwMDExNzA1fQ.N9SSL3dNSKYg-irhVGg8XcfNhbFM6O8I9FX4TAus0-8

{
    "total": 1000000,
    "status": "Paid",
    "prepaid": 0,
    "arriveDate": "2019-12-12",
    "departureDate": "2019-12-12"
}

###
POST  http://localhost:5000/api/ticket
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY0OTc1MjUwNSwiZXhwIjoxNjUwMDExNzA1fQ.N9SSL3dNSKYg-irhVGg8XcfNhbFM6O8I9FX4TAus0-8

{
   "customer": "62518e2e050b10088b0f8167", 
   "room": "6251497554b6a63896ae4cc3"
}

###
DELETE http://localhost:5000/api/ticket/6257cad59f4faba74efb16a2
Content-Type: application/json

###
POST http://localhost:5000/api/ticket/list
Content-Type: application/json

{
    "room": "6251496854b6a63896ae4cbf",
    "startDate": "2022-04-14T07:30:27.610+00:00"
}

###
GET http://localhost:5000/api/roomType
Content-Type: application/json

###
POST http://localhost:5000/api/roomType
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MDU4OTA4NywiZXhwIjoxNjUwODQ4Mjg3fQ.PGZr_7gCWiDccVQyJYpCbeXG3zadSKNcsi60qePMb54

{
    "name": "Phòng Mới",
    "description": "Phòng mới"
}

###
PUT http://localhost:5000/api/roomType/62625eac83f3f75418fbfca4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MDU4OTA4NywiZXhwIjoxNjUwODQ4Mjg3fQ.PGZr_7gCWiDccVQyJYpCbeXG3zadSKNcsi60qePMb54

{
    "name": "Phòng Mới",
    "description": "Phòng mới"
}
###
DELETE http://localhost:5000/api/roomType/6257e1f8bc2808e113b7dd7a
Content-Type: application/json

###
GET http://localhost:5000/api/customer
Content-Type: application/json

###
POST http://localhost:5000/api/customer
Content-Type: application/json

{
    "name": "Nguyễn Văn A",
    "email": "123456789",
    "phone": "123456789",
    "address": "Thua Thien Hue",
    "type": "Local",
    "ID": "12345678911"
}

###
DELETE http://localhost:5000/api/customer/6257e52692b3716d066108b5
Content-Type: application/json

###
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "mie6996", 
    "email": "nguyenxuanphat060301@gmail.com", 
    "password": "123456"
}


###
DELETE http://localhost:5000/api/user/6257eafd874ffd5f1df66e85
Content-Type: application/json

###

GET http://localhost:5000/api/roomType
Content-Type: application/json


###
GET http://localhost:5000/api/charge
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmUxOTdlY2YwNzlmZTYyNmQxZTE5MyIsImlhdCI6MTY1MTQxOTY5MCwiZXhwIjoxNjUxNjc4ODkwfQ.RSt59BHJgr-aTHlKugn_0yeHjdChfwcLpbOEVNNx-KU

###
POST http://localhost:5000/api/charge
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZkYzI2ZDIxNjI2YzZiNTE4NGM0MCIsImlhdCI6MTY1MDU5ODg3NSwiZXhwIjoxNjUwODU4MDc1fQ.MUa1brI_26fU1Sj2gJo_cl3BpHhWZDOWoykEi9zfMMI

{
    "name": "Phòng VIP",
    "FirstBlock": "3",
    "FirstBlockCharge": "300000",
    "OvertimeCharge": "300000",
    "OverNightCharge": "300000",
    "DateCharge": "300000",
    "SurCharge": "300000"
}

###
GET http://localhost:5000/api/user
Content-Type: application/json

###
GET http://localhost:5000/api/room/findroom
Content-Type: application/json

###
PUT http://localhost:5000/api/permissons/625fdc26d21626c6b5184c40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MTM3MDU4OCwiZXhwIjoxNjUxNjI5Nzg4fQ.hVDeiVJOt9XOsk4XThrb0HFKG2DfvAqWMs0oJ4pQ56M

{
    "hasPrice": false,
    "hasRental": false,
    "hasRoom": true,
    "hasType": false,
    "isAdmin": false,
}

###
GET http://localhost:5000/api/booking/bookbyblock
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MTY4MzA5NiwiZXhwIjoxNjUxOTQyMjk2fQ.Gs38x2NS4J-RfMOoSAZFRh7es5zlHkO_S_W5yZNEu0A

###
POST  http://localhost:5000/api/invoice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MTY4MzA5NiwiZXhwIjoxNjUxOTQyMjk2fQ.Gs38x2NS4J-RfMOoSAZFRh7es5zlHkO_S_W5yZNEu0A

{
    "total":1000,
    "ticket": {
        "_id":"6272ccf8ca3760c173140c0e"
    }
}

###
GET   http://localhost:5000/api/invoice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTEyYjUzODIwZmRlOTk0NGQ5MzIwOSIsImlhdCI6MTY1MTY4MzA5NiwiZXhwIjoxNjUxOTQyMjk2fQ.Gs38x2NS4J-RfMOoSAZFRh7es5zlHkO_S_W5yZNEu0A


